server:
  port: 5555

zuul:
  routes:
    accounts:
      path: /security/**
      url: http://localhost:9001/knowledge/
    questions:
      path: /questions/**
      url: http://localhost:9002/knowledge/
    exams:
      path: /exams/**
      url: http://localhost:9003/knowledge/